BusTicketBookingSystem/BusTicketBookingSystem/Controllers/People/UserRoleController.cs
using BusTicketBookingSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BusTicketBookingSystem.Controllers
{
    public class UserRoleController : Controller
    {
        private OperationDataContext context = null;

        public UserRoleController()
        {
            context = new OperationDataContext();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserRoleModel model)
        {
            var q = from p in context.UserRoles
                    where p.Username == model.Username && p.Password == model.Password
                    select p;

            if (q.Any())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        // GET: UserRole
        public ActionResult Index()
        {
            // create the userRoleList variable
            List<UserRoleModel> userRoleList = new List<UserRoleModel>();

            // perform linq operation
            var query = from userRole in context.UserRoles
                        join role in context.Roles
                        on userRole.RoleID equals role.Id
                        select new UserRoleModel
                        {
                            Id = userRole.Id,
                            Username = userRole.Username,
                            Password = userRole.Password,
                            RoleName = role.Name,
                        };

            // store the query to list
            userRoleList = query.ToList();

            return View(userRoleList);
        }

        // GET: UserRole/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UserRole/Create
        public ActionResult Create()
        {
            UserRoleModel model = new UserRoleModel();
            PrepareRole(model);

            return View(model);
        }

        // POST: UserRole/Create
        [HttpPost]
        public ActionResult Create(UserRoleModel model)
        {
            try
            {
                // TODO: Add insert logic here
                UserRole userRole = new UserRole()
                {
                    Username = model.Username,
                    Password = model.Password,
                    RoleID = model.RoleID
                };

                context.UserRoles.InsertOnSubmit(userRole);
                context.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: UserRole/Edit/5
        public ActionResult Edit(int id)
        {
            UserRoleModel model = context.UserRoles.Where(some => some.Id == id).Select(
                some => new UserRoleModel()
                {
                    Id = some.Id,
                    Username = some.Username,
                    Password = some.Password,
                    RoleID = some.RoleID
                }).SingleOrDefault();

            PrepareRole(model);
            return View(model);
        }

        // POST: UserRole/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, UserRoleModel model)
        {
            try
            {
                // TODO: Add update logic here
                UserRole userRole = context.UserRoles.Where(some => some.Id == model.Id).Single<UserRole>();
                userRole.Username = model.Username;
                userRole.Password = model.Password;
                userRole.RoleID = model.RoleID;
                context.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserRole/Delete/5
        public ActionResult Delete(int id)
        {
            UserRoleModel model = context.UserRoles.Where(some => some.Id == id).Select(
                some => new UserRoleModel()
                {
                    Id = some.Id,
                    Username = some.Username,
                    Password = some.Password,
                    RoleID = some.RoleID
                }).SingleOrDefault();

            PrepareRole(model);
            return View(model);
        }

        // POST: UserRole/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, UserRoleModel model)
        {
            try
            {
                // TODO: Add delete logic here
                UserRole userRole = context.UserRoles.Where(some => some.Id == model.Id).Single<UserRole>();

                context.UserRoles.DeleteOnSubmit(userRole);
                context.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private void PrepareRole (UserRoleModel model)
        {
            model.Roles = context.Roles.AsQueryable<Role>().Select(x =>
                          new SelectListItem()
                          {
                            Text = x.Name,
                            Value = x.Id.ToString()
                          });
        }
    }
}

BusTicketBookingSystem/BusTicketBookingSystem/Views/UserRole/Create.cshtml
@model BusTicketBookingSystem.Models.UserRoleModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserRoleModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model=>model.RoleID,Model.Roles, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BusTicketBookingSystem/BusTicketBookingSystem/Views/UserRole/Delete.cshtml
@model BusTicketBookingSystem.Models.UserRoleModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserRoleModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BusTicketBookingSystem/BusTicketBookingSystem/Views/UserRole/Edit.cshtml
@model BusTicketBookingSystem.Models.UserRoleModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserRoleModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoleID, Model.Roles, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BusTicketBookingSystem/BusTicketBookingSystem/Views/UserRole/Index.cshtml
@model IEnumerable<BusTicketBookingSystem.Models.UserRoleModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

BusTicketBookingSystem/BusTicketBookingSystem/Views/UserRole/Login.cshtml
@model BusTicketBookingSystem.Models.UserRoleModel

@{
    ViewBag.Title = "Login";
}

@*<h2>Login</h2>
@using (Html.BeginForm("Index", "Home", FormMethod.Post))
{
    <fieldset>
        <legend>Mvc Simple Login Application Demo</legend>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @if (@ViewBag.Message != null)
        {
            <div style="border: 1px solid red">
                @ViewBag.Message
            </div>
        }
        <table>
            <tr>
                <td>@Html.LabelFor(a => a.Username)</td>
                <td>@Html.TextBoxFor(a => a.Username)</td>
                <td>@Html.ValidationMessageFor(a => a.Username)</td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(a => a.Password)
                </td>
                <td>
                    @Html.PasswordFor(a => a.Password)
                </td>
                <td>
                    @Html.ValidationMessageFor(a => a.Password)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Login" />
                </td>
                <td></td>
            </tr>
        </table>
    </fieldset>
}*@

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "UserRole", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Username, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register as a new user", "Register")
                </p>
            }
        </section>
    </div>
</div>